# Generated by Django 4.2 on 2023-04-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_finish']},
        ),
        migrations.AddField(
            model_name='author',
            name='edition',
            field=models.CharField(blank=True, help_text="What edition is the book e.g 1'st edition", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number Guide </a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
