# Generated by Django 4.2 on 2023-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_options_author_edition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='author',
            name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, help_text="What edition is the book e.g 1'st edition", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
